[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/template',
    'pallets/token',
    'pallets/trade',
    'pallets/contract',
    'pallets/identity',
    'pallets/parliament',
    'runtime',
    'primitives',
]
