version: "3.5"
networks:
  vppnetwork:
    name: vppnetwork
    
    
services:
  vpp-front:
    image: develop/vpp-front:release
    container_name: vpp-front
    ports:
      - "8887:8887"
    environment:
      ENDPOINT: ws:node-template:9944
      PORT: 8887
    restart: always
    networks:
      vppnetwork:
        aliases: 
          - vppnetwork