version: "3.5"
networks:
  vppnetwork:
    name: vppnetwork
    
    
services:
  vpp-front:
    image: baidang201/vpp-front:release
    container_name: vpp-front
    ports:
      - "8887:8887"
    environment:
      ENDPOINT: ws:vpp.com:9944
      PORT: 8887
    extra_hosts:
      - "vpp.com:8.210.143.28"
    restart: always
    networks:
      vppnetwork:
        aliases: 
          - vppnetwork